"""fresh

Revision ID: 2650055e896a
Revises: 
Create Date: 2022-08-26 14:29:02.012241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2650055e896a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('addressid', sa.Integer(), nullable=False),
    sa.Column('addressstreet', sa.String(length=50), nullable=False),
    sa.Column('addressnumber', sa.Integer(), nullable=False),
    sa.Column('addresszip', sa.String(length=50), nullable=False),
    sa.Column('addresscounty', sa.String(length=50), nullable=False),
    sa.Column('addresscountry', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('addressid')
    )
    op.create_table('sexes',
    sa.Column('sexid', sa.Integer(), nullable=False),
    sa.Column('sexname', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('sexid'),
    sa.UniqueConstraint('sexname')
    )
    op.create_table('tags',
    sa.Column('tagid', sa.Integer(), nullable=False),
    sa.Column('tagname', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('tagid')
    )
    op.create_table('parties',
    sa.Column('partyid', sa.Integer(), nullable=False),
    sa.Column('partytitle', sa.String(length=50), nullable=True),
    sa.Column('partyaddressid', sa.Integer(), nullable=False),
    sa.Column('partytime', sa.DateTime(), nullable=False),
    sa.Column('partyduration', sa.Time(), nullable=False),
    sa.Column('partyagemin', sa.Integer(), nullable=False),
    sa.Column('partyagemax', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['partyaddressid'], ['address.addressid'], ),
    sa.PrimaryKeyConstraint('partyid')
    )
    op.create_table('users',
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('usersexid', sa.Integer(), nullable=False),
    sa.Column('useraddressid', sa.Integer(), nullable=False),
    sa.Column('userage', sa.Integer(), nullable=False),
    sa.Column('useremail', sa.String(length=50), nullable=False),
    sa.Column('userpassword', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['useraddressid'], ['address.addressid'], ),
    sa.ForeignKeyConstraint(['usersexid'], ['sexes.sexid'], ),
    sa.PrimaryKeyConstraint('userid'),
    sa.UniqueConstraint('username')
    )
    op.create_table('party_sexes',
    sa.Column('partyid', sa.Integer(), nullable=False),
    sa.Column('sexid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['partyid'], ['parties.partyid'], ),
    sa.ForeignKeyConstraint(['sexid'], ['sexes.sexid'], ),
    sa.PrimaryKeyConstraint('partyid', 'sexid')
    )
    op.create_table('party_tags',
    sa.Column('partyid', sa.Integer(), nullable=False),
    sa.Column('tagid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['partyid'], ['parties.partyid'], ),
    sa.ForeignKeyConstraint(['tagid'], ['tags.tagid'], ),
    sa.PrimaryKeyConstraint('partyid', 'tagid')
    )
    op.create_table('party_users',
    sa.Column('partyId', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['partyId'], ['parties.partyid'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.userid'], ),
    sa.PrimaryKeyConstraint('partyId', 'userId')
    )
    op.create_table('user_tag',
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('tagid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tagid'], ['tags.tagid'], ),
    sa.ForeignKeyConstraint(['userid'], ['users.userid'], ),
    sa.PrimaryKeyConstraint('userid', 'tagid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_tag')
    op.drop_table('party_users')
    op.drop_table('party_tags')
    op.drop_table('party_sexes')
    op.drop_table('users')
    op.drop_table('parties')
    op.drop_table('tags')
    op.drop_table('sexes')
    op.drop_table('address')
    # ### end Alembic commands ###
