"""[MOD]_PARTY:time+duration->starttime+endtime

Revision ID: 4776386cc9f2
Revises: 2650055e896a
Create Date: 2022-08-31 14:35:05.454701

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4776386cc9f2'
down_revision = '2650055e896a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parties', sa.Column('partytimeend', sa.DateTime(), nullable=False))
    op.add_column('parties', sa.Column('partytimestart', sa.DateTime(), nullable=False))
    op.drop_column('parties', 'partytime')
    op.drop_column('parties', 'partyduration')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parties', sa.Column('partyduration', postgresql.TIME(), autoincrement=False, nullable=False))
    op.add_column('parties', sa.Column('partytime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('parties', 'partytimestart')
    op.drop_column('parties', 'partytimeend')
    # ### end Alembic commands ###
