"""basic_schema

Revision ID: 7a620a49c341
Revises: f64a5cb2370d
Create Date: 2022-08-25 13:26:18.449711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a620a49c341'
down_revision = 'f64a5cb2370d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('locationid', sa.Integer(), nullable=False),
    sa.Column('locationstreet', sa.String(length=50), nullable=True),
    sa.Column('locationnumber', sa.Integer(), nullable=True),
    sa.Column('locationzip', sa.String(length=50), nullable=True),
    sa.Column('locationcounty', sa.String(length=50), nullable=True),
    sa.Column('locationcountry', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('locationid')
    )
    op.create_table('sexes',
    sa.Column('sexid', sa.Integer(), nullable=False),
    sa.Column('sexname', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('sexid')
    )
    op.create_table('tags',
    sa.Column('tagid', sa.Integer(), nullable=False),
    sa.Column('tagname', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('tagid')
    )
    op.create_table('parties',
    sa.Column('partyid', sa.Integer(), nullable=False),
    sa.Column('partytitle', sa.String(length=50), nullable=True),
    sa.Column('partylocationid', sa.Integer(), nullable=True),
    sa.Column('partytime', sa.DateTime(), nullable=True),
    sa.Column('partyduration', sa.Time(), nullable=True),
    sa.Column('partyagemin', sa.Integer(), nullable=False),
    sa.Column('partyagemax', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['partylocationid'], ['locations.locationid'], ),
    sa.PrimaryKeyConstraint('partyid')
    )
    op.create_table('party_sexes',
    sa.Column('partyid', sa.Integer(), nullable=False),
    sa.Column('sexid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['partyid'], ['parties.partyid'], ),
    sa.ForeignKeyConstraint(['sexid'], ['sexes.sexid'], ),
    sa.PrimaryKeyConstraint('partyid', 'sexid')
    )
    op.create_table('party_tags',
    sa.Column('partyid', sa.Integer(), nullable=False),
    sa.Column('tagid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['partyid'], ['parties.partyid'], ),
    sa.ForeignKeyConstraint(['tagid'], ['tags.tagid'], ),
    sa.PrimaryKeyConstraint('partyid', 'tagid')
    )
    op.create_table('party_users',
    sa.Column('partyId', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['partyId'], ['parties.partyid'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.userid'], ),
    sa.PrimaryKeyConstraint('partyId', 'userId')
    )
    op.create_table('user_tags',
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('tagid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tagid'], ['tags.tagid'], ),
    sa.ForeignKeyConstraint(['userid'], ['users.userid'], ),
    sa.PrimaryKeyConstraint('userid', 'tagid')
    )
    op.add_column('users', sa.Column('useraddress', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('userage', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('usersexid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'locations', ['useraddress'], ['locationid'])
    op.create_foreign_key(None, 'users', 'sexes', ['usersexid'], ['sexid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'usersexid')
    op.drop_column('users', 'userage')
    op.drop_column('users', 'useraddress')
    op.drop_table('user_tags')
    op.drop_table('party_users')
    op.drop_table('party_tags')
    op.drop_table('party_sexes')
    op.drop_table('parties')
    op.drop_table('tags')
    op.drop_table('sexes')
    op.drop_table('locations')
    # ### end Alembic commands ###
