"""useraddress->useraddressid

Revision ID: 92fe9434d67a
Revises: ca676a4edbb5
Create Date: 2022-08-25 14:40:06.212712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92fe9434d67a'
down_revision = 'ca676a4edbb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('useraddressid', sa.Integer(), nullable=True))
    op.drop_constraint('users_useraddress_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'locations', ['useraddressid'], ['locationid'])
    op.drop_column('users', 'useraddress')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('useraddress', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_useraddress_fkey', 'users', 'locations', ['useraddress'], ['locationid'])
    op.drop_column('users', 'useraddressid')
    # ### end Alembic commands ###
