"""fix

Revision ID: ca676a4edbb5
Revises: 7a620a49c341
Create Date: 2022-08-25 13:55:42.767670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca676a4edbb5'
down_revision = '7a620a49c341'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_tag',
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('tagid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tagid'], ['tags.tagid'], ),
    sa.ForeignKeyConstraint(['userid'], ['users.userid'], ),
    sa.PrimaryKeyConstraint('userid', 'tagid')
    )
    op.drop_table('user_tags')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_tags',
    sa.Column('userid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tagid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tagid'], ['tags.tagid'], name='user_tags_tagid_fkey'),
    sa.ForeignKeyConstraint(['userid'], ['users.userid'], name='user_tags_userid_fkey'),
    sa.PrimaryKeyConstraint('userid', 'tagid', name='user_tags_pkey')
    )
    op.drop_table('user_tag')
    # ### end Alembic commands ###
